### ISSUE TITLE
failed to deploy kafka via strimzi using e2e test environment

### ISSUE THREAD

**Issue by KalmanMeth** [netobserv/flowlogs-pipeline#159]
various Forbidden messages.

content of kubectl log:

Auto-detected KUBERNETES_SERVICE_DNS_DOMAIN: cluster.local
+ exec /usr/bin/tini -w -e 143 -- java -Dlog4j2.configurationFile=file:/opt/strimzi/custom-config/log4j2.properties -Dvertx.cache
DirBase=/tmp/vertx-cache -Djava.security.egd=file:/dev/./urandom --illegal-access=deny -classpath lib/io.strimzi.cluster-operator
-0.28.0.jar:lib/io.netty.netty-common-4.1.71.Final.jar:lib/io.fabric8.kubernetes-model-certificates-5.12.0.jar:lib/io.fabric8.ope
nshift-model-hive-5.12.0.jar:lib/io.fabric8.openshift-model-installer-5.12.0.jar:lib/com.fasterxml.jackson.datatype.jackson-datat
ype-jsr310-2.13.1.jar:lib/io.fabric8.openshift-model-console-5.12.0.jar:lib/io.strimzi.kafka-oauth-server-0.10.0.jar:lib/io.netty
.netty-codec-http2-4.1.71.Final.jar:lib/io.fabric8.openshift-model-storageversionmigrator-5.12.0.jar:lib/io.fabric8.kubernetes-mo
del-policy-5.12.0.jar:lib/org.hdrhistogram.HdrHistogram-2.1.11.jar:lib/com.fasterxml.jackson.core.jackson-databind-2.11.3.jar:lib
/io.fabric8.openshift-model-miscellaneous-5.12.0.jar:lib/com.squareup.okhttp3.logging-interceptor-3.12.12.jar:lib/io.fabric8.open
shift-model-operator-5.12.0.jar:lib/io.fabric8.kubernetes-model-core-5.12.0.jar:lib/org.apache.zookeeper.zookeeper-jute-3.6.3.jar
:lib/io.netty.netty-handler-4.1.71.Final.jar:lib/org.apache.logging.log4j.log4j-core-2.17.1.jar:lib/org.apache.zookeeper.zookeepe
r-3.6.3.jar:lib/net.minidev.accessors-smart-2.4.7.jar:lib/com.fasterxml.jackson.dataformat.jackson-dataformat-yaml-2.10.5.jar:lib
/com.github.mifmif.generex-1.0.2.jar:lib/io.strimzi.config-model-0.28.0.jar:lib/io.fabric8.kubernetes-model-common-5.12.0.jar:lib
/io.fabric8.kubernetes-model-autoscaling-5.12.0.jar:lib/io.fabric8.openshift-model-tuned-5.12.0.jar:lib/org.yaml.snakeyaml-1.26.j
ar:lib/io.netty.netty-resolver-dns-4.1.71.Final.jar:lib/io.fabric8.kubernetes-model-events-5.12.0.jar:lib/io.fabric8.openshift-cl
ient-5.12.0.jar:lib/io.netty.netty-codec-socks-4.1.71.Final.jar:lib/io.netty.netty-handler-proxy-4.1.71.Final.jar:lib/io.fabric8.
kubernetes-model-rbac-5.12.0.jar:lib/io.netty.netty-resolver-4.1.71.Final.jar:lib/com.jayway.jsonpath.json-path-2.6.0.jar:lib/net
.minidev.json-smart-2.4.7.jar:lib/io.strimzi.kafka-oauth-server-plain-0.10.0.jar:lib/io.strimzi.api-0.28.0.jar:lib/io.fabric8.zjs
onpatch-0.3.0.jar:lib/io.fabric8.kubernetes-model-storageclass-5.12.0.jar:lib/io.fabric8.kubernetes-model-networking-5.12.0.jar:l
ib/io.netty.netty-codec-dns-4.1.71.Final.jar:lib/io.fabric8.openshift-model-monitoring-5.12.0.jar:lib/io.strimzi.kafka-oauth-comm
on-0.10.0.jar:lib/io.netty.netty-transport-native-unix-common-4.1.71.Final.jar:lib/io.netty.netty-transport-native-epoll-4.1.71.F
inal.jar:lib/io.strimzi.certificate-manager-0.28.0.jar:lib/org.quartz-scheduler.quartz-2.3.2.jar:lib/io.fabric8.kubernetes-model-
node-5.12.0.jar:lib/io.prometheus.simpleclient_common-0.7.0.jar:lib/io.fabric8.kubernetes-model-flowcontrol-5.12.0.jar:lib/org.ap
ache.logging.log4j.log4j-slf4j-impl-2.17.1.jar:lib/io.strimzi.crd-annotations-0.28.0.jar:lib/io.netty.netty-buffer-4.1.71.Final.j
ar:lib/org.lz4.lz4-java-1.8.0.jar:lib/io.vertx.vertx-core-4.2.4.jar:lib/com.squareup.okio.okio-1.15.0.jar:lib/org.xerial.snappy.s
nappy-java-1.1.8.4.jar:lib/io.fabric8.openshift-model-machineconfig-5.12.0.jar:lib/io.fabric8.openshift-model-machine-5.12.0.jar:
lib/io.strimzi.operator-common-0.28.0.jar:lib/io.prometheus.simpleclient-0.7.0.jar:lib/io.fabric8.kubernetes-model-metrics-5.12.0
.jar:lib/io.netty.netty-transport-native-epoll-4.1.71.Final-linux-x86_64.jar:lib/io.fabric8.openshift-model-operatorhub-5.12.0.ja
r:lib/org.apache.yetus.audience-annotations-0.5.0.jar:lib/com.fasterxml.jackson.core.jackson-annotations-2.11.3.jar:lib/io.fabric
8.openshift-model-5.12.0.jar:lib/io.micrometer.micrometer-core-1.3.1.jar:lib/io.fabric8.kubernetes-model-admissionregistration-5.
12.0.jar:lib/io.fabric8.kubernetes-model-apps-5.12.0.jar:lib/io.netty.netty-codec-4.1.71.Final.jar:lib/io.fabric8.kubernetes-mode
l-extensions-5.12.0.jar:lib/com.nimbusds.nimbus-jose-jwt-9.10.jar:lib/io.fabric8.kubernetes-model-batch-5.12.0.jar:lib/io.netty.n
etty-codec-http-4.1.71.Final.jar:lib/com.squareup.okhttp3.okhttp-3.12.12.jar:lib/io.fabric8.kubernetes-model-scheduling-5.12.0.jar:lib/com.github.luben.zstd-jni-1.5.0-4.jar:lib/io.fabric8.openshift-model-clusterautoscaling-5.12.0.jar:lib/com.fasterxml.jackso
n.core.jackson-core-2.11.3.jar:lib/com.github.stephenc.jcip.jcip-annotations-1.0-1.jar:lib/io.strimzi.kafka-oauth-client-0.10.0.j
ar:lib/io.fabric8.kubernetes-client-5.12.0.jar:lib/io.fabric8.kubernetes-model-coordination-5.12.0.jar:lib/io.fabric8.kubernetes-
model-discovery-5.12.0.jar:lib/io.fabric8.kubernetes-model-apiextensions-5.12.0.jar:lib/dk.brics.automaton.automaton-1.11-8.jar:l
ib/io.fabric8.openshift-model-whereabouts-5.12.0.jar:lib/org.apache.logging.log4j.log4j-api-2.17.1.jar:lib/io.netty.netty-transpo
rt-classes-epoll-4.1.71.Final.jar:lib/org.slf4j.slf4j-api-1.7.25.jar:lib/org.latencyutils.LatencyUtils-2.0.3.jar:lib/io.vertx.ver
tx-micrometer-metrics-4.2.4.jar:lib/io.netty.netty-tcnative-classes-2.0.46.Final.jar:lib/io.netty.netty-transport-4.1.71.Final.ja
r:lib/org.apache.kafka.kafka-clients-3.1.0.jar:lib/io.micrometer.micrometer-registry-prometheus-1.3.1.jar io.strimzi.operator.clu
ster.Main
2022-03-29 11:00:40 INFO  Main:60 - ClusterOperator 0.28.0 is starting
2022-03-29 11:00:41 INFO  Main:62 - Cluster Operator configuration is ClusterOperatorConfig(namespaces=[test],reconciliationInter
valMs=120000,operationTimeoutMs=300000,connectBuildTimeoutMs=300000,createClusterRoles=false,networkPolicyGeneration=true,version
s=versions{3.0.0={proto: 3.0 msg: 3.0 kafka-image: quay.io/strimzi/kafka:0.28.0-kafka-3.0.0 connect-image: quay.io/strimzi/kafka:
0.28.0-kafka-3.0.0 mirrormaker-image: quay.io/strimzi/kafka:0.28.0-kafka-3.0.0 mirrormaker2-image: quay.io/strimzi/kafka:0.28.0-k
afka-3.0.0}, 3.1.0={proto: 3.1 msg: 3.1 kafka-image: quay.io/strimzi/kafka:0.28.0-kafka-3.1.0 connect-image: quay.io/strimzi/kafk
a:0.28.0-kafka-3.1.0 mirrormaker-image: quay.io/strimzi/kafka:0.28.0-kafka-3.1.0 mirrormaker2-image: quay.io/strimzi/kafka:0.28.0
-kafka-3.1.0}},imagePullPolicy=null,imagePullSecrets=null,operatorNamespace=test,operatorNamespaceLabels=null,rbacScope=CLUSTER,c
ustomResourceSelector=null,featureGates=FeatureGates(controlPlaneListener=true,ServiceAccountPatching=true,UseStrimziPodSets=fals
e),zkAdminSessionTimeoutMs=10000,dnsCacheTtlSec=30)
2022-03-29 11:00:46 WARN  PlatformFeaturesAvailability:157 - API Group route.openshift.io is not supported
2022-03-29 11:00:46 WARN  PlatformFeaturesAvailability:157 - API Group build.openshift.io is not supported
2022-03-29 11:00:46 WARN  PlatformFeaturesAvailability:157 - API Group image.openshift.io is not supported
2022-03-29 11:00:46 INFO  Main:81 - Environment facts gathered: PlatformFeaturesAvailability(KubernetesVersion=1.21,OpenShiftRout
es=false,OpenShiftBuilds=false,OpenShiftImageStreams=false)
2022-03-29 11:00:46 INFO  Util:303 - Using config:
        PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
        container: oci
        STRIMZI_DEFAULT_KAFKA_BRIDGE_IMAGE: quay.io/strimzi/kafka-bridge:0.21.4
        KUBERNETES_PORT: tcp://10.96.0.1:443
        STRIMZI_KAFKA_MIRROR_MAKER_IMAGES: 3.0.0=quay.io/strimzi/kafka:0.28.0-kafka-3.0.0
3.1.0=quay.io/strimzi/kafka:0.28.0-kafka-3.1.0

        STRIMZI_DEFAULT_TOPIC_OPERATOR_IMAGE: quay.io/strimzi/operator:0.28.0
        JAVA_HOME: /usr/lib/jvm/jre-11
        JAVA_OPTS:  -Dlog4j2.configurationFile=file:/opt/strimzi/custom-config/log4j2.properties -Dvertx.cacheDirBase=/tmp/vertx-
cache -Djava.security.egd=file:/dev/./urandom  --illegal-access=deny
        STRIMZI_FULL_RECONCILIATION_INTERVAL_MS: 120000
        KUBERNETES_SERVICE_HOST: 10.96.0.1
        JAVA_CLASSPATH: lib/io.strimzi.cluster-operator-0.28.0.jar:lib/io.netty.netty-common-4.1.71.Final.jar:lib/io.fabric8.kube
rnetes-model-certificates-5.12.0.jar:lib/io.fabric8.openshift-model-hive-5.12.0.jar:lib/io.fabric8.openshift-model-installer-5.12
.0.jar:lib/com.fasterxml.jackson.datatype.jackson-datatype-jsr310-2.13.1.jar:lib/io.fabric8.openshift-model-console-5.12.0.jar:li
b/io.strimzi.kafka-oauth-server-0.10.0.jar:lib/io.netty.netty-codec-http2-4.1.71.Final.jar:lib/io.fabric8.openshift-model-storage
versionmigrator-5.12.0.jar:lib/io.fabric8.kubernetes-model-policy-5.12.0.jar:lib/org.hdrhistogram.HdrHistogram-2.1.11.jar:lib/com
.fasterxml.jackson.core.jackson-databind-2.11.3.jar:lib/io.fabric8.openshift-model-miscellaneous-5.12.0.jar:lib/com.squareup.okht
tp3.logging-interceptor-3.12.12.jar:lib/io.fabric8.openshift-model-operator-5.12.0.jar:lib/io.fabric8.kubernetes-model-core-5.12.
0.jar:lib/org.apache.zookeeper.zookeeper-jute-3.6.3.jar:lib/io.netty.netty-handler-4.1.71.Final.jar:lib/org.apache.logging.log4j.
log4j-core-2.17.1.jar:lib/org.apache.zookeeper.zookeeper-3.6.3.jar:lib/net.minidev.accessors-smart-2.4.7.jar:lib/com.fasterxml.ja
ckson.dataformat.jackson-dataformat-yaml-2.10.5.jar:lib/com.github.mifmif.generex-1.0.2.jar:lib/io.strimzi.config-model-0.28.0.ja
r:lib/io.fabric8.kubernetes-model-common-5.12.0.jar:lib/io.fabric8.kubernetes-model-autoscaling-5.12.0.jar:lib/io.fabric8.openshi
ft-model-tuned-5.12.0.jar:lib/org.yaml.snakeyaml-1.26.jar:lib/io.netty.netty-resolver-dns-4.1.71.Final.jar:lib/io.fabric8.kuberne
tes-model-events-5.12.0.jar:lib/io.fabric8.openshift-client-5.12.0.jar:lib/io.netty.netty-codec-socks-4.1.71.Final.jar:lib/io.net
ty.netty-handler-proxy-4.1.71.Final.jar:lib/io.fabric8.kubernetes-model-rbac-5.12.0.jar:lib/io.netty.netty-resolver-4.1.71.Final.
jar:lib/com.jayway.jsonpath.json-path-2.6.0.jar:lib/net.minidev.json-smart-2.4.7.jar:lib/io.strimzi.kafka-oauth-server-plain-0.10
.0.jar:lib/io.strimzi.api-0.28.0.jar:lib/io.fabric8.zjsonpatch-0.3.0.jar:lib/io.fabric8.kubernetes-model-storageclass-5.12.0.jar:
lib/io.fabric8.kubernetes-model-networking-5.12.0.jar:lib/io.netty.netty-codec-dns-4.1.71.Final.jar:lib/io.fabric8.openshift-mode
l-monitoring-5.12.0.jar:lib/io.strimzi.kafka-oauth-common-0.10.0.jar:lib/io.netty.netty-transport-native-unix-common-4.1.71.Final
.jar:lib/io.netty.netty-transport-native-epoll-4.1.71.Final.jar:lib/io.strimzi.certificate-manager-0.28.0.jar:lib/org.quartz-sche
duler.quartz-2.3.2.jar:lib/io.fabric8.kubernetes-model-node-5.12.0.jar:lib/io.prometheus.simpleclient_common-0.7.0.jar:lib/io.fab
ric8.kubernetes-model-flowcontrol-5.12.0.jar:lib/org.apache.logging.log4j.log4j-slf4j-impl-2.17.1.jar:lib/io.strimzi.crd-annotati
ons-0.28.0.jar:lib/io.netty.netty-buffer-4.1.71.Final.jar:lib/org.lz4.lz4-java-1.8.0.jar:lib/io.vertx.vertx-core-4.2.4.jar:lib/co
m.squareup.okio.okio-1.15.0.jar:lib/org.xerial.snappy.snappy-java-1.1.8.4.jar:lib/io.fabric8.openshift-model-machineconfig-5.12.0
.jar:lib/io.fabric8.openshift-model-machine-5.12.0.jar:lib/io.strimzi.operator-common-0.28.0.jar:lib/io.prometheus.simpleclient-0
.7.0.jar:lib/io.fabric8.kubernetes-model-metrics-5.12.0.jar:lib/io.netty.netty-transport-native-epoll-4.1.71.Final-linux-x86_64.j
ar:lib/io.fabric8.openshift-model-operatorhub-5.12.0.jar:lib/org.apache.yetus.audience-annotations-0.5.0.jar:lib/com.fasterxml.ja
ckson.core.jackson-annotations-2.11.3.jar:lib/io.fabric8.openshift-model-5.12.0.jar:lib/io.micrometer.micrometer-core-1.3.1.jar:l
ib/io.fabric8.kubernetes-model-admissionregistration-5.12.0.jar:lib/io.fabric8.kubernetes-model-apps-5.12.0.jar:lib/io.netty.netty-codec-4.1.71.Final.jar:lib/io.fabric8.kubernetes-model-extensions-5.12.0.jar:lib/com.nimbusds.nimbus-jose-jwt-9.10.jar:lib/io.f
abric8.kubernetes-model-batch-5.12.0.jar:lib/io.netty.netty-codec-http-4.1.71.Final.jar:lib/com.squareup.okhttp3.okhttp-3.12.12.j
ar:lib/io.fabric8.kubernetes-model-scheduling-5.12.0.jar:lib/com.github.luben.zstd-jni-1.5.0-4.jar:lib/io.fabric8.openshift-model
-clusterautoscaling-5.12.0.jar:lib/com.fasterxml.jackson.core.jackson-core-2.11.3.jar:lib/com.github.stephenc.jcip.jcip-annotatio
ns-1.0-1.jar:lib/io.strimzi.kafka-oauth-client-0.10.0.jar:lib/io.fabric8.kubernetes-client-5.12.0.jar:lib/io.fabric8.kubernetes-m
odel-coordination-5.12.0.jar:lib/io.fabric8.kubernetes-model-discovery-5.12.0.jar:lib/io.fabric8.kubernetes-model-apiextensions-5
.12.0.jar:lib/dk.brics.automaton.automaton-1.11-8.jar:lib/io.fabric8.openshift-model-whereabouts-5.12.0.jar:lib/org.apache.loggin
g.log4j.log4j-api-2.17.1.jar:lib/io.netty.netty-transport-classes-epoll-4.1.71.Final.jar:lib/org.slf4j.slf4j-api-1.7.25.jar:lib/o
rg.latencyutils.LatencyUtils-2.0.3.jar:lib/io.vertx.vertx-micrometer-metrics-4.2.4.jar:lib/io.netty.netty-tcnative-classes-2.0.46
.Final.jar:lib/io.netty.netty-transport-4.1.71.Final.jar:lib/org.apache.kafka.kafka-clients-3.1.0.jar:lib/io.micrometer.micromete
r-registry-prometheus-1.3.1.jar
        STRIMZI_DEFAULT_TLS_SIDECAR_CRUISE_CONTROL_IMAGE: quay.io/strimzi/kafka:0.28.0-kafka-3.1.0
        STRIMZI_DEFAULT_CRUISE_CONTROL_IMAGE: quay.io/strimzi/kafka:0.28.0-kafka-3.1.0
        STRIMZI_HOME: /opt/strimzi
        PWD: /opt/strimzi
        TINI_VERSION: v0.19.0
        KUBERNETES_PORT_443_TCP: tcp://10.96.0.1:443
        STRIMZI_OPERATION_TIMEOUT_MS: 300000
        JAVA_MAIN: io.strimzi.operator.cluster.Main
        KUBERNETES_PORT_443_TCP_ADDR: 10.96.0.1
        STRIMZI_VERSION: 0.28.0
        STRIMZI_DEFAULT_JMXTRANS_IMAGE: quay.io/strimzi/jmxtrans:0.28.0
        STRIMZI_NAMESPACE: test
        STRIMZI_DEFAULT_KANIKO_EXECUTOR_IMAGE: quay.io/strimzi/kaniko-executor:0.28.0
        TINI_SHA256_S390X: 931b70a182af879ca249ae9de87ef68423121b38d235c78997fafc680ceab32d
        STRIMZI_KAFKA_MIRROR_MAKER_2_IMAGES: 3.0.0=quay.io/strimzi/kafka:0.28.0-kafka-3.0.0
3.1.0=quay.io/strimzi/kafka:0.28.0-kafka-3.1.0

        STRIMZI_DEFAULT_MAVEN_BUILDER: quay.io/strimzi/maven-builder:0.28.0
        KUBERNETES_PORT_443_TCP_PROTO: tcp
        STRIMZI_DEFAULT_USER_OPERATOR_IMAGE: quay.io/strimzi/operator:0.28.0
        STRIMZI_FEATURE_GATES:
        KUBERNETES_SERVICE_PORT: 443
        STRIMZI_DEFAULT_KAFKA_EXPORTER_IMAGE: quay.io/strimzi/kafka:0.28.0-kafka-3.1.0
        TINI_SHA256_ARM64: 07952557df20bfd2a95f9bef198b445e006171969499a1d361bd9e6f8e5e0e81
        STRIMZI_DEFAULT_KAFKA_INIT_IMAGE: quay.io/strimzi/operator:0.28.0
        TINI_SHA256_PPC64LE: 3f658420974768e40810001a038c29d003728c5fe86da211cff5059e48cfdfde
        TINI_SHA256_AMD64: 93dcc18adc78c65a028a84799ecf8ad40c936fdfc5f2a57b1acda5a8117fa82c
        KUBERNETES_SERVICE_DNS_DOMAIN: cluster.local
        HOSTNAME: strimzi-cluster-operator-587cb79468-7jlfr
        STRIMZI_KAFKA_CONNECT_IMAGES: 3.0.0=quay.io/strimzi/kafka:0.28.0-kafka-3.0.0
3.1.0=quay.io/strimzi/kafka:0.28.0-kafka-3.1.0

        STRIMZI_KAFKA_IMAGES: 3.0.0=quay.io/strimzi/kafka:0.28.0-kafka-3.0.0
3.1.0=quay.io/strimzi/kafka:0.28.0-kafka-3.1.0

        KUBERNETES_PORT_443_TCP_PORT: 443
        KUBERNETES_SERVICE_PORT_HTTPS: 443
        STRIMZI_DEFAULT_TLS_SIDECAR_ENTITY_OPERATOR_IMAGE: quay.io/strimzi/kafka:0.28.0-kafka-3.1.0
        SHLVL: 0
        HOME: /home/strimzi
        MALLOC_ARENA_MAX: 2
        STRIMZI_OPERATOR_NAMESPACE: test

2022-03-29 11:00:47 INFO  ClusterOperator:79 - Creating ClusterOperator for namespace test
2022-03-29 11:00:47 INFO  ClusterOperator:94 - Starting ClusterOperator for namespace test
2022-03-29 11:00:47 WARN  WatchConnectionManager:125 - Exec Failure: HTTP 403, Status: 403 - Forbidden
2022-03-29 11:00:47 WARN  WatchConnectionManager:125 - Exec Failure: HTTP 403, Status: 403 - Forbidden
2022-03-29 11:00:47 WARN  WatchConnectionManager:125 - Exec Failure: HTTP 403, Status: 403 - Forbidden
2022-03-29 11:00:47 WARN  WatchConnectionManager:125 - Exec Failure: HTTP 403, Status: 403 - Forbidden
2022-03-29 11:00:47 WARN  WatchConnectionManager:125 - Exec Failure: HTTP 403, Status: 403 - Forbidden
2022-03-29 11:00:47 WARN  WatchConnectionManager:125 - Exec Failure: HTTP 403, Status: 403 - Forbidden
2022-03-29 11:00:47 WARN  WatchConnectionManager:125 - Exec Failure: HTTP 403, Status: 403 - Forbidden
2022-03-29 11:00:47 ERROR Main:154 - Cluster Operator verticle in namespace test failed to start
io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: GET at: https://10.96.0.1/apis/kafka.strimzi.io/v1beta
2/namespaces/test/kafkas?allowWatchBookmarks=true&watch=true. Message: Forbidden.
        at io.fabric8.kubernetes.client.dsl.base.OperationSupport.requestFailure(OperationSupport.java:683) ~[io.fabric8.kubernet
es-client-5.12.0.jar:?]
        at io.fabric8.kubernetes.client.dsl.base.OperationSupport.requestFailure(OperationSupport.java:662) ~[io.fabric8.kubernet
es-client-5.12.0.jar:?]
        at io.fabric8.kubernetes.client.dsl.internal.WatchConnectionManager.lambda$run$2(WatchConnectionManager.java:126) ~[io.fa
bric8.kubernetes-client-5.12.0.jar:?]
        at java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:930) ~[?:?]
        at java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:907) ~[?:?]
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) ~[?:?]
        at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2088) ~[?:?]
        at io.fabric8.kubernetes.client.okhttp.OkHttpWebSocketImpl$BuilderImpl$1.onFailure(OkHttpWebSocketImpl.java:66) ~[io.fabr
ic8.kubernetes-client-5.12.0.jar:?]
        at okhttp3.internal.ws.RealWebSocket.failWebSocket(RealWebSocket.java:571) ~[com.squareup.okhttp3.okhttp-3.12.12.jar:?]
        at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:198) ~[com.squareup.okhttp3.okhttp-3.12.12.jar:?]
        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:203) ~[com.squareup.okhttp3.okhttp-3.12.12.jar:?]
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32) ~[com.squareup.okhttp3.okhttp-3.12.12.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
        at java.lang.Thread.run(Thread.java:829) [?:?]
        Suppressed: java.lang.Throwable: waiting here
                at io.fabric8.kubernetes.client.utils.Utils.waitUntilReady(Utils.java:168) ~[io.fabric8.kubernetes-client-5.12.0.
jar:?]
                at io.fabric8.kubernetes.client.utils.Utils.waitUntilReadyOrFail(Utils.java:179) ~[io.fabric8.kubernetes-client-5
.12.0.jar:?]
                at io.fabric8.kubernetes.client.dsl.internal.WatchConnectionManager.waitUntilReady(WatchConnectionManager.java:96
) ~[io.fabric8.kubernetes-client-5.12.0.jar:?]
                at io.fabric8.kubernetes.client.dsl.base.BaseOperation.watch(BaseOperation.java:572) ~[io.fabric8.kubernetes-clie
nt-5.12.0.jar:?]
                at io.fabric8.kubernetes.client.dsl.base.BaseOperation.watch(BaseOperation.java:547) ~[io.fabric8.kubernetes-clie
nt-5.12.0.jar:?]
                at io.fabric8.kubernetes.client.dsl.base.BaseOperation.watch(BaseOperation.java:83) ~[io.fabric8.kubernetes-clien
t-5.12.0.jar:?]
                at io.strimzi.operator.common.operator.resource.AbstractWatchableResourceOperator.watch(AbstractWatchableResource        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:203) ~[com.squareup.okhttp3.okhttp-3.12.12.jar:?]
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32) ~[com.squareup.okhttp3.okhttp-3.12.12.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
        at java.lang.Thread.run(Thread.java:829) [?:?]
        Suppressed: java.lang.Throwable: waiting here
                at io.fabric8.kubernetes.client.utils.Utils.waitUntilReady(Utils.java:168) ~[io.fabric8.kubernetes-client-5.12.0.
jar:?]
                at io.fabric8.kubernetes.client.utils.Utils.waitUntilReadyOrFail(Utils.java:179) ~[io.fabric8.kubernetes-client-5
.12.0.jar:?]
                at io.fabric8.kubernetes.client.dsl.internal.WatchConnectionManager.waitUntilReady(WatchConnectionManager.java:96
) ~[io.fabric8.kubernetes-client-5.12.0.jar:?]
                at io.fabric8.kubernetes.client.dsl.base.BaseOperation.watch(BaseOperation.java:572) ~[io.fabric8.kubernetes-clie
nt-5.12.0.jar:?]
                at io.fabric8.kubernetes.client.dsl.base.BaseOperation.watch(BaseOperation.java:547) ~[io.fabric8.kubernetes-clie
nt-5.12.0.jar:?]
                at io.fabric8.kubernetes.client.dsl.base.BaseOperation.watch(BaseOperation.java:83) ~[io.fabric8.kubernetes-clien
t-5.12.0.jar:?]
                at io.strimzi.operator.common.operator.resource.AbstractWatchableResourceOperator.watch(AbstractWatchableResource
Operator.java:58) ~[io.strimzi.operator-common-0.28.0.jar:0.28.0]
                at io.strimzi.operator.common.AbstractOperator.lambda$createWatch$21(AbstractOperator.java:491) ~[io.strimzi.oper
ator-common-0.28.0.jar:0.28.0]
                at io.strimzi.operator.common.Util.lambda$async$0(Util.java:76) ~[io.strimzi.operator-common-0.28.0.jar:0.28.0]
                at io.vertx.core.impl.ContextImpl.lambda$null$0(ContextImpl.java:159) ~[io.vertx.vertx-core-4.2.4.jar:4.2.4]
                at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:100) ~[io.vertx.vertx-core-4.2.4.jar:4.2.4]
                at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$1(ContextImpl.java:157) ~[io.vertx.vertx-core-4.2.4.jar:
4.2.4]
                at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76) ~[io.vertx.vertx-core-4.2.4.jar:4.2.4]
                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
                at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [io.netty.netty-common-4
.1.71.Final.jar:4.1.71.Final]
                at java.lang.Thread.run(Thread.java:829) [?:?]

**Comment by eranra** [comment]
Resolved by https://github.com/netobserv/flowlogs-pipeline/pull/182
